### ISSUE TITLE
Error: Please assign at least one day and one night image

### ISSUE THREAD

**Issue by Theraa0** [gdstewart/ddw-theme-creator#13]
![image](https://user-images.githubusercontent.com/62468600/121787973-d22d9600-cbc9-11eb-9b9f-7ad26fdb1e12.png)
I uploaded a .heic file and assigned them, as you can see in the image, but I keep getting the "Please assign at least one day and one night image." Error. Tested two different files and both of them resulted in this.

**Comment by Theraa0** [comment]
I'm just stupid, don't mind me. If you have the same issue as me, look to the right of the image.

**Comment by gdstewart** [comment]
I'll be the first to admit the UI could be a little more streamlined. Hopefully one day I can get around to making it a bit less confusing.
